name: Terraform

on: push

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v2
        with:
          repository: evops-boe/actions@master
          token: ${{ secrets.SHARED_ACTIONS_PRIVATE_KEY }}
          path: shared-actions
      - uses: ./shared-actions/actions/terraform
