name: Terraform

on: push

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      # Clones main repo
      - uses: actions/checkout@v2
      # Clones shared actions repository
      - uses: actions/checkout@v2
        with:
          repository: evops-boe/actions
          ref: master
          ssh-key: ${{ secrets.SHARED_ACTIONS_PRIVATE_KEY }}
          persist-credentials: "false"
          path: shared-actions
      - uses: ./shared-actions/actions/terraform


